[#ftl]
[@b.head/]
  [@b.toolbar title="收费明细配置"]
    bar.addBack();
  [/@]
  [@b.form name="feeDefaultForm" action="!save" target="feeDefaults" theme="list"]
    [#assign elementSTYLE = "width: 200px"/]
    [#assign s = "feeDefault_"/]
    [@b.textfield label="起始年级" name="feeDefault.fromGrade" value=(feeDefault.fromGrade)! required="true" check="match('yearMonth')" maxlength="6" style=elementSTYLE comment="正确格式：2017-3；错误格式：2017-10"/]
    [@b.textfield label="截止年级" name="feeDefault.toGrade" value=(feeDefault.toGrade)! required="true" check="match('yearMonth')" maxlength="6" style=elementSTYLE comment="格式同上"/]
    [@b.select id=s + "span" label="学历层次" name="feeDefault.level.id" items=levels?sort_by(["name"]) empty="..." value=(feeDefault.level.id)! required="true" style=elementSTYLE/]
    [@b.select id=s + "department" label="院系所" name="feeDefault.department.id" items=departments?sort_by(["name"]) empty="..." value=(feeDefault.department.id)! style=elementSTYLE/]
    [@b.select id=s + "major" label="专业" name="feeDefault.major.id" items=majors?sort_by(["name"]) empty="..." value=(feeDefault.major.id)! required="true" style=elementSTYLE/]
    [@b.select label="交费类型" name="feeDefault.type.id" items=feeTypes?sort_by(["name"]) value=(feeDefault.type.id)! empty="..." required="true" style=elementSTYLE/]
    [@b.textfield label="总额" name="feeDefault.value" value=(feeDefault.value)!0 required="true" maxlength="64" check="match('number')" style=elementSTYLE/]
    [@b.textarea label="备注" name="feeDefault.remark" value=(feeDefault.remark?html)! maxlength="200" rows="3" style=elementSTYLE/]
    [@b.formfoot]
      <input type="hidden" name="feeDefault.id" value="${(feeDefault.id)!}"/>
      <input type="hidden" name="_params" value="${Parameters["_params"]!}"/>
      [@b.submit value="提交" target="feeDefaults"/]
    [/@]
  [/@]
[@b.foot/]
